// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudSpeechV2
import GoogleCloudLocation
import GoogleLongRunning
import GoogleWKT

func sample(client: SpeechClient, projectId: String, locationId: String, phraseSetId: String)
  async throws
{
  let poller = try await client.deletePhraseSetPollingUntilDone(
    request: DeletePhraseSetRequest()
      .with {
        $0.name = "projects/\(projectId)/locations/\(locationId)/phraseSets/\(phraseSetId)"
      }
  )
  let response = try await poller.wait()
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudSpeechV2.SpeechClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        phraseSetId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
