// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Final results for a single file.
public struct BatchRecognizeFileResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Error if one was encountered.
  public var error: GoogleRpc.Status? = nil

  public var metadata: RecognitionResponseMetadata? = nil

  /// Deprecated. Use `cloud_storage_result.native_format_uri` instead.
  @available(*, deprecated)
  public var uri: Swift.String = Swift.String()

  /// Deprecated. Use `inline_result.transcript` instead.
  @available(*, deprecated)
  public var transcript: BatchRecognizeResults? = nil

  public var result: OneOf_Result? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchRecognizeFileResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchRecognizeFileResult().with { $0.error = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let error = CodingKeys(stringValue: "error")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let cloudStorageResult = CodingKeys(stringValue: "cloudStorageResult")
    static let inlineResult = CodingKeys(stringValue: "inlineResult")
    static let uri = CodingKeys(stringValue: "uri")
    static let transcript = CodingKeys(stringValue: "transcript")

    static let _knownKeys: Set<Swift.String> = [
      "error",
      "metadata",
      "cloudStorageResult",
      "inlineResult",
      "uri",
      "transcript",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.metadata = try container.decodeIfPresent(
      RecognitionResponseMetadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    self.transcript = try container.decodeIfPresent(BatchRecognizeResults.self, forKey: .transcript)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let cloudStorageResult = try container.decodeIfPresent(
      CloudStorageResult?.self, forKey: .cloudStorageResult)
    {
      try resultCheckAndSet(.cloudStorageResult(cloudStorageResult))
    }
    if let inlineResult = try container.decodeIfPresent(InlineResult?.self, forKey: .inlineResult) {
      try resultCheckAndSet(.inlineResult(inlineResult))
    }
    self.result = result
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.uri, forKey: .uri)
    try container.encodeIfPresent(self.transcript, forKey: .transcript)

    if let choice = self.result {
      switch choice {
      case .cloudStorageResult(let value):
        try container.encode(value, forKey: .cloudStorageResult)
      case .inlineResult(let value):
        try container.encode(value, forKey: .inlineResult)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// Recognition results written to Cloud Storage. This is
    /// populated only when
    /// [GcsOutputConfig][google.cloud.speech.v2.GcsOutputConfig] is set in
    /// the
    /// [RecognitionOutputConfig][[google.cloud.speech.v2.RecognitionOutputConfig].
    ///
    /// [google.cloud.speech.v2.GcsOutputConfig]: <doc:GcsOutputConfig>
    indirect case cloudStorageResult(CloudStorageResult?)
    /// Recognition results. This is populated only when
    /// [InlineOutputConfig][google.cloud.speech.v2.InlineOutputConfig] is set in
    /// the
    /// [RecognitionOutputConfig][[google.cloud.speech.v2.RecognitionOutputConfig].
    ///
    /// [google.cloud.speech.v2.InlineOutputConfig]: <doc:InlineOutputConfig>
    indirect case inlineResult(InlineResult?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.BatchRecognizeFileResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
