// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Final results written to Cloud Storage.
public struct CloudStorageResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Cloud Storage URI to which recognition results were written.
  public var uri: Swift.String = Swift.String()

  /// The Cloud Storage URI to which recognition results were written as VTT
  /// formatted captions. This is populated only when `VTT` output is requested.
  public var vttFormatUri: Swift.String = Swift.String()

  /// The Cloud Storage URI to which recognition results were written as SRT
  /// formatted captions. This is populated only when `SRT` output is requested.
  public var srtFormatUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudStorageResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudStorageResult().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uri = CodingKeys(stringValue: "uri")
    static let vttFormatUri = CodingKeys(stringValue: "vttFormatUri")
    static let srtFormatUri = CodingKeys(stringValue: "srtFormatUri")

    static let _knownKeys: Set<Swift.String> = [
      "uri",
      "vttFormatUri",
      "srtFormatUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vttFormatUri) {
      self.vttFormatUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .srtFormatUri) {
      self.srtFormatUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.vttFormatUri, forKey: .vttFormatUri)
    try container.encode(self.srtFormatUri, forKey: .srtFormatUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.CloudStorageResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
