// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for the
/// [CreateCustomClass][google.cloud.speech.v2.Speech.CreateCustomClass] method.
///
/// [google.cloud.speech.v2.Speech.CreateCustomClass]: <doc:SpeechClient/createCustomClass(request:options:)>
public struct CreateCustomClassRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The CustomClass to create.
  public var customClass: CustomClass? = nil

  /// If set, validate the request and preview the CustomClass, but do not
  /// actually create it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// The ID to use for the CustomClass, which will become the final component of
  /// the CustomClass's resource name.
  ///
  /// This value should be 4-63 characters, and valid characters
  /// are /[a-z][0-9]-/.
  public var customClassId: Swift.String = Swift.String()

  /// Required. The project and location where this CustomClass will be created.
  /// The expected format is `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateCustomClassRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateCustomClassRequest().with { $0.customClass = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let customClass = CodingKeys(stringValue: "customClass")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let customClassId = CodingKeys(stringValue: "customClassId")
    static let parent = CodingKeys(stringValue: "parent")

    static let _knownKeys: Set<Swift.String> = [
      "customClass",
      "validateOnly",
      "customClassId",
      "parent",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.customClass = try container.decodeIfPresent(CustomClass.self, forKey: .customClass)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customClassId) {
      self.customClassId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.customClass, forKey: .customClass)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.customClassId, forKey: .customClassId)
    try container.encode(self.parent, forKey: .parent)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.CreateCustomClassRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
