// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Explicitly specified decoding parameters.
public struct ExplicitDecodingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Encoding of the audio data sent for recognition.
  public var encoding: ExplicitDecodingConfig.AudioEncoding = ExplicitDecodingConfig.AudioEncoding()

  /// Optional. Sample rate in Hertz of the audio data sent for recognition.
  /// Valid values are: 8000-48000, and 16000 is optimal. For best results, set
  /// the sampling rate of the audio source to 16000 Hz. If that's not possible,
  /// use the native sample rate of the audio source (instead of resampling).
  /// Note that this field is marked as OPTIONAL for backward compatibility
  /// reasons. It is (and has always been) effectively REQUIRED.
  public var sampleRateHertz: Swift.Int32 = Swift.Int32()

  /// Optional. Number of channels present in the audio data sent for
  /// recognition. Note that this field is marked as OPTIONAL for backward
  /// compatibility reasons. It is (and has always been) effectively REQUIRED.
  ///
  /// The maximum allowed value is 8.
  public var audioChannelCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExplicitDecodingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExplicitDecodingConfig().with { $0.encoding = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let encoding = CodingKeys(stringValue: "encoding")
    static let sampleRateHertz = CodingKeys(stringValue: "sampleRateHertz")
    static let audioChannelCount = CodingKeys(stringValue: "audioChannelCount")

    static let _knownKeys: Set<Swift.String> = [
      "encoding",
      "sampleRateHertz",
      "audioChannelCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      ExplicitDecodingConfig.AudioEncoding.self, forKey: .encoding)
    {
      self.encoding = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sampleRateHertz) {
      self.sampleRateHertz = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .audioChannelCount) {
      self.audioChannelCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.encoding, forKey: .encoding)
    try container.encode(self.sampleRateHertz, forKey: .sampleRateHertz)
    try container.encode(self.audioChannelCount, forKey: .audioChannelCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Supported audio data encodings.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AudioEncoding: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Headerless 16-bit signed little-endian PCM samples.
    case linear16
    /// Headerless 8-bit companded mulaw samples.
    case mulaw
    /// Headerless 8-bit companded alaw samples.
    case alaw
    /// AMR frames with an rfc4867.5 header.
    case amr
    /// AMR-WB frames with an rfc4867.5 header.
    case amrWb
    /// FLAC frames in the "native FLAC" container format.
    case flac
    /// MPEG audio frames with optional (ignored) ID3 metadata.
    case mp3
    /// Opus audio frames in an Ogg container.
    case oggOpus
    /// Opus audio frames in a WebM container.
    case webmOpus
    /// AAC audio frames in an MP4 container.
    case mp4Aac
    /// AAC audio frames in an M4A container.
    case m4AAac
    /// AAC audio frames in an MOV container.
    case movAac
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .linear16: return 1
      case .mulaw: return 2
      case .alaw: return 3
      case .amr: return 4
      case .amrWb: return 5
      case .flac: return 6
      case .mp3: return 7
      case .oggOpus: return 8
      case .webmOpus: return 9
      case .mp4Aac: return 10
      case .m4AAac: return 11
      case .movAac: return 12
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUDIO_ENCODING_UNSPECIFIED"
      case .linear16: return "LINEAR16"
      case .mulaw: return "MULAW"
      case .alaw: return "ALAW"
      case .amr: return "AMR"
      case .amrWb: return "AMR_WB"
      case .flac: return "FLAC"
      case .mp3: return "MP3"
      case .oggOpus: return "OGG_OPUS"
      case .webmOpus: return "WEBM_OPUS"
      case .mp4Aac: return "MP4_AAC"
      case .m4AAac: return "M4A_AAC"
      case .movAac: return "MOV_AAC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AudioEncoding/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUDIO_ENCODING_UNSPECIFIED": self = .unspecified
      case "LINEAR16": self = .linear16
      case "MULAW": self = .mulaw
      case "ALAW": self = .alaw
      case "AMR": self = .amr
      case "AMR_WB": self = .amrWb
      case "FLAC": self = .flac
      case "MP3": self = .mp3
      case "OGG_OPUS": self = .oggOpus
      case "WEBM_OPUS": self = .webmOpus
      case "MP4_AAC": self = .mp4Aac
      case "M4A_AAC": self = .m4AAac
      case "MOV_AAC": self = .movAac
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AudioEncoding/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .linear16
      case 2: self = .mulaw
      case 3: self = .alaw
      case 4: self = .amr
      case 5: self = .amrWb
      case 6: self = .flac
      case 7: self = .mp3
      case 8: self = .oggOpus
      case 9: self = .webmOpus
      case 10: self = .mp4Aac
      case 11: self = .m4AAac
      case 12: self = .movAac
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AUDIO_ENCODING_UNSPECIFIED")
      case .linear16: return try container.encode("LINEAR16")
      case .mulaw: return try container.encode("MULAW")
      case .alaw: return try container.encode("ALAW")
      case .amr: return try container.encode("AMR")
      case .amrWb: return try container.encode("AMR_WB")
      case .flac: return try container.encode("FLAC")
      case .mp3: return try container.encode("MP3")
      case .oggOpus: return try container.encode("OGG_OPUS")
      case .webmOpus: return try container.encode("WEBM_OPUS")
      case .mp4Aac: return try container.encode("MP4_AAC")
      case .m4AAac: return try container.encode("M4A_AAC")
      case .movAac: return try container.encode("MOV_AAC")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.ExplicitDecodingConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
