// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for the format of the results stored to `output`.
public struct OutputFormatConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Configuration for the native output format. If this field is set or if no
  /// other output format field is set, then transcripts will be written to the
  /// sink in the native format.
  public var native: NativeOutputFileFormatConfig? = nil

  /// Configuration for the VTT output format. If this field is set, then
  /// transcripts will be written to the sink in the VTT format.
  public var vtt: VttOutputFileFormatConfig? = nil

  /// Configuration for the SRT output format. If this field is set, then
  /// transcripts will be written to the sink in the SRT format.
  public var srt: SrtOutputFileFormatConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OutputFormatConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutputFormatConfig().with { $0.native = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let native = CodingKeys(stringValue: "native")
    static let vtt = CodingKeys(stringValue: "vtt")
    static let srt = CodingKeys(stringValue: "srt")

    static let _knownKeys: Set<Swift.String> = [
      "native",
      "vtt",
      "srt",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.native = try container.decodeIfPresent(NativeOutputFileFormatConfig.self, forKey: .native)
    self.vtt = try container.decodeIfPresent(VttOutputFileFormatConfig.self, forKey: .vtt)
    self.srt = try container.decodeIfPresent(SrtOutputFileFormatConfig.self, forKey: .srt)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.native, forKey: .native)
    try container.encodeIfPresent(self.vtt, forKey: .vtt)
    try container.encodeIfPresent(self.srt, forKey: .srt)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.OutputFormatConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
