// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration options for the output(s) of recognition.
public struct RecognitionOutputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Configuration for the format of the results stored to `output`.
  /// If unspecified transcripts will be written in the `NATIVE` format only.
  public var outputFormatConfig: OutputFormatConfig? = nil

  public var output: OutputOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RecognitionOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecognitionOutputConfig().with { $0.gcsOutputConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsOutputConfig = CodingKeys(stringValue: "gcsOutputConfig")
    static let inlineResponseConfig = CodingKeys(stringValue: "inlineResponseConfig")
    static let outputFormatConfig = CodingKeys(stringValue: "outputFormatConfig")

    static let _knownKeys: Set<Swift.String> = [
      "gcsOutputConfig",
      "inlineResponseConfig",
      "outputFormatConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.outputFormatConfig = try container.decodeIfPresent(
      OutputFormatConfig.self, forKey: .outputFormatConfig)

    var output: OutputOneOf? = nil
    let outputCheckAndSet = {
      if output != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'output'"))
      }
      output = $0
    }
    if let gcsOutputConfig = try container.decodeIfPresent(
      GcsOutputConfig?.self, forKey: .gcsOutputConfig)
    {
      try outputCheckAndSet(.gcsOutputConfig(gcsOutputConfig))
    }
    if let inlineResponseConfig = try container.decodeIfPresent(
      InlineOutputConfig?.self, forKey: .inlineResponseConfig)
    {
      try outputCheckAndSet(.inlineResponseConfig(inlineResponseConfig))
    }
    self.output = output
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.outputFormatConfig, forKey: .outputFormatConfig)

    if let choice = self.output {
      switch choice {
      case .gcsOutputConfig(let value):
        try container.encode(value, forKey: .gcsOutputConfig)
      case .inlineResponseConfig(let value):
        try container.encode(value, forKey: .inlineResponseConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OutputOneOf: Codable, Equatable, Sendable {
    /// If this message is populated, recognition results are written to the
    /// provided Google Cloud Storage URI.
    indirect case gcsOutputConfig(GcsOutputConfig?)
    /// If this message is populated, recognition results are provided in the
    /// [BatchRecognizeResponse][google.cloud.speech.v2.BatchRecognizeResponse]
    /// message of the Operation when completed. This is only supported when
    /// calling [BatchRecognize][google.cloud.speech.v2.Speech.BatchRecognize]
    /// with just one audio file.
    ///
    /// [google.cloud.speech.v2.BatchRecognizeResponse]: <doc:BatchRecognizeResponse>
    /// [google.cloud.speech.v2.Speech.BatchRecognize]: <doc:SpeechClient/batchRecognize(request:options:)>
    indirect case inlineResponseConfig(InlineOutputConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.RecognitionOutputConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
