// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for the
/// [Recognize][google.cloud.speech.v2.Speech.Recognize] method. Either
/// `content` or `uri` must be supplied. Supplying both or neither returns
/// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]. See [content
/// limits](https://cloud.google.com/speech-to-text/quotas#content).
///
/// [google.cloud.speech.v2.Speech.Recognize]: <doc:SpeechClient/recognize(request:options:)>
public struct RecognizeRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Recognizer to use during recognition. The
  /// expected format is
  /// `projects/{project}/locations/{location}/recognizers/{recognizer}`. The
  /// {recognizer} segment may be set to `_` to use an empty implicit Recognizer.
  public var recognizer: Swift.String = Swift.String()

  /// Features and audio metadata to use for the Automatic Speech Recognition.
  /// This field in combination with the
  /// [config_mask][google.cloud.speech.v2.RecognizeRequest.config_mask] field
  /// can be used to override parts of the
  /// [default_recognition_config][google.cloud.speech.v2.Recognizer.default_recognition_config]
  /// of the Recognizer resource.
  ///
  /// [google.cloud.speech.v2.RecognizeRequest.config_mask]: <doc:RecognizeRequest/configMask>
  /// [google.cloud.speech.v2.Recognizer.default_recognition_config]: <doc:Recognizer/defaultRecognitionConfig>
  public var config: RecognitionConfig? = nil

  /// The list of fields in
  /// [config][google.cloud.speech.v2.RecognizeRequest.config] that override the
  /// values in the
  /// [default_recognition_config][google.cloud.speech.v2.Recognizer.default_recognition_config]
  /// of the recognizer during this recognition request. If no mask is provided,
  /// all non-default valued fields in
  /// [config][google.cloud.speech.v2.RecognizeRequest.config] override the
  /// values in the recognizer for this recognition request. If a mask is
  /// provided, only the fields listed in the mask override the config in the
  /// recognizer for this recognition request. If a wildcard (`*`) is provided,
  /// [config][google.cloud.speech.v2.RecognizeRequest.config] completely
  /// overrides and replaces the config in the recognizer for this recognition
  /// request.
  ///
  /// [google.cloud.speech.v2.RecognizeRequest.config]: <doc:RecognizeRequest/config>
  /// [google.cloud.speech.v2.Recognizer.default_recognition_config]: <doc:Recognizer/defaultRecognitionConfig>
  public var configMask: GoogleWKT.WKTFieldMask? = nil

  /// The audio source, which is either inline content or a Google Cloud
  /// Storage URI.
  public var audioSource: OneOf_AudioSource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RecognizeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecognizeRequest().with { $0.recognizer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let recognizer = CodingKeys(stringValue: "recognizer")
    static let config = CodingKeys(stringValue: "config")
    static let configMask = CodingKeys(stringValue: "configMask")
    static let content = CodingKeys(stringValue: "content")
    static let uri = CodingKeys(stringValue: "uri")

    static let _knownKeys: Set<Swift.String> = [
      "recognizer",
      "config",
      "configMask",
      "content",
      "uri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recognizer) {
      self.recognizer = value
    }
    self.config = try container.decodeIfPresent(RecognitionConfig.self, forKey: .config)
    self.configMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .configMask)

    var audioSource: OneOf_AudioSource? = nil
    let audioSourceCheckAndSet = {
      if audioSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'audioSource'"))
      }
      audioSource = $0
    }
    if let content = try container.decodeIfPresent(Foundation.Data.self, forKey: .content) {
      try audioSourceCheckAndSet(.content(content))
    }
    if let uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      try audioSourceCheckAndSet(.uri(uri))
    }
    self.audioSource = audioSource
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.recognizer, forKey: .recognizer)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encodeIfPresent(self.configMask, forKey: .configMask)

    if let choice = self.audioSource {
      switch choice {
      case .content(let value):
        try container.encode(value, forKey: .content)
      case .uri(let value):
        try container.encode(value, forKey: .uri)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The audio source, which is either inline content or a Google Cloud
  /// Storage URI.
  public enum OneOf_AudioSource: Codable, Equatable, Sendable {
    /// The audio data bytes encoded as specified in
    /// [RecognitionConfig][google.cloud.speech.v2.RecognitionConfig]. As
    /// with all bytes fields, proto buffers use a pure binary representation,
    /// whereas JSON representations use base64.
    ///
    /// [google.cloud.speech.v2.RecognitionConfig]: <doc:RecognitionConfig>
    case content(Foundation.Data)
    /// URI that points to a file that contains audio data bytes as specified in
    /// [RecognitionConfig][google.cloud.speech.v2.RecognitionConfig]. The file
    /// must not be compressed (for example, gzip). Currently, only Google Cloud
    /// Storage URIs are supported, which must be specified in the following
    /// format: `gs://bucket_name/object_name` (other URI formats return
    /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]). For more
    /// information, see [Request
    /// URIs](https://cloud.google.com/storage/docs/reference-uris).
    ///
    /// [google.cloud.speech.v2.RecognitionConfig]: <doc:RecognitionConfig>
    case uri(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.RecognizeRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
