// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Provides information to the Recognizer that specifies how to process the
/// recognition request.
public struct RecognitionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Which model to use for recognition requests. Select the model
  /// best suited to your domain to get best results.
  ///
  /// Guidance for choosing which model to use can be found in the [Transcription
  /// Models
  /// Documentation](https://cloud.google.com/speech-to-text/v2/docs/transcription-model)
  /// and the models supported in each region can be found in the [Table Of
  /// Supported
  /// Models](https://cloud.google.com/speech-to-text/v2/docs/speech-to-text-supported-languages).
  public var model: Swift.String = Swift.String()

  /// Optional. The language of the supplied audio as a
  /// [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag.
  /// Language tags are normalized to BCP-47 before they are used eg "en-us"
  /// becomes "en-US".
  ///
  /// Supported languages for each model are listed in the [Table of Supported
  /// Models](https://cloud.google.com/speech-to-text/v2/docs/speech-to-text-supported-languages).
  ///
  /// If additional languages are provided, recognition result will contain
  /// recognition in the most likely language detected. The recognition result
  /// will include the language tag of the language detected in the audio.
  public var languageCodes: [Swift.String] = []

  /// Speech recognition features to enable.
  public var features: RecognitionFeatures? = nil

  /// Speech adaptation context that weights recognizer predictions for specific
  /// words and phrases.
  public var adaptation: SpeechAdaptation? = nil

  /// Optional. Use transcription normalization to automatically replace parts of
  /// the transcript with phrases of your choosing. For StreamingRecognize, this
  /// normalization only applies to stable partial transcripts (stability > 0.8)
  /// and final transcripts.
  public var transcriptNormalization: TranscriptNormalization? = nil

  /// Optional. Optional configuration used to automatically run translation on
  /// the given audio to the desired language for supported models.
  public var translationConfig: TranslationConfig? = nil

  /// Optional. Optional denoiser config. May not be supported for all models
  /// and may have no effect.
  public var denoiserConfig: DenoiserConfig? = nil

  /// Decoding parameters for audio being sent for recognition.
  public var decodingConfig: DecodingConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RecognitionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecognitionConfig().with { $0.autoDecodingConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let autoDecodingConfig = CodingKeys(stringValue: "autoDecodingConfig")
    static let explicitDecodingConfig = CodingKeys(stringValue: "explicitDecodingConfig")
    static let model = CodingKeys(stringValue: "model")
    static let languageCodes = CodingKeys(stringValue: "languageCodes")
    static let features = CodingKeys(stringValue: "features")
    static let adaptation = CodingKeys(stringValue: "adaptation")
    static let transcriptNormalization = CodingKeys(stringValue: "transcriptNormalization")
    static let translationConfig = CodingKeys(stringValue: "translationConfig")
    static let denoiserConfig = CodingKeys(stringValue: "denoiserConfig")

    static let _knownKeys: Set<Swift.String> = [
      "autoDecodingConfig",
      "explicitDecodingConfig",
      "model",
      "languageCodes",
      "features",
      "adaptation",
      "transcriptNormalization",
      "translationConfig",
      "denoiserConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languageCodes) {
      self.languageCodes = value
    }
    self.features = try container.decodeIfPresent(RecognitionFeatures.self, forKey: .features)
    self.adaptation = try container.decodeIfPresent(SpeechAdaptation.self, forKey: .adaptation)
    self.transcriptNormalization = try container.decodeIfPresent(
      TranscriptNormalization.self, forKey: .transcriptNormalization)
    self.translationConfig = try container.decodeIfPresent(
      TranslationConfig.self, forKey: .translationConfig)
    self.denoiserConfig = try container.decodeIfPresent(
      DenoiserConfig.self, forKey: .denoiserConfig)

    var decodingConfig: DecodingConfigOneOf? = nil
    let decodingConfigCheckAndSet = {
      if decodingConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'decodingConfig'"))
      }
      decodingConfig = $0
    }
    if let autoDecodingConfig = try container.decodeIfPresent(
      AutoDetectDecodingConfig?.self, forKey: .autoDecodingConfig)
    {
      try decodingConfigCheckAndSet(.autoDecodingConfig(autoDecodingConfig))
    }
    if let explicitDecodingConfig = try container.decodeIfPresent(
      ExplicitDecodingConfig?.self, forKey: .explicitDecodingConfig)
    {
      try decodingConfigCheckAndSet(.explicitDecodingConfig(explicitDecodingConfig))
    }
    self.decodingConfig = decodingConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.model, forKey: .model)
    try container.encode(self.languageCodes, forKey: .languageCodes)
    try container.encodeIfPresent(self.features, forKey: .features)
    try container.encodeIfPresent(self.adaptation, forKey: .adaptation)
    try container.encodeIfPresent(self.transcriptNormalization, forKey: .transcriptNormalization)
    try container.encodeIfPresent(self.translationConfig, forKey: .translationConfig)
    try container.encodeIfPresent(self.denoiserConfig, forKey: .denoiserConfig)

    if let choice = self.decodingConfig {
      switch choice {
      case .autoDecodingConfig(let value):
        try container.encode(value, forKey: .autoDecodingConfig)
      case .explicitDecodingConfig(let value):
        try container.encode(value, forKey: .explicitDecodingConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Decoding parameters for audio being sent for recognition.
  public enum DecodingConfigOneOf: Codable, Equatable, Sendable {
    /// Automatically detect decoding parameters.
    /// Preferred for supported formats.
    indirect case autoDecodingConfig(AutoDetectDecodingConfig?)
    /// Explicitly specified decoding parameters.
    /// Required if using headerless PCM audio (linear16, mulaw, alaw).
    indirect case explicitDecodingConfig(ExplicitDecodingConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.RecognitionConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
