// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Enables speech transcription and resource management.
///
/// @Snippet(path: "SpeechQuickstart")
public final class SpeechClient: Clients.SpeechProtocol, Sendable {
  let inner: any Clients.SpeechStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `SpeechClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.SpeechStub = try Clients.SpeechTransport(options)
    inner = Clients.SpeechRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SpeechLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_CreateRecognizer")
  public func createRecognizer(
    request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createRecognizer(request: request, options: options)
  }

  /// Creates a [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_CreateRecognizer")
  public func createRecognizerPollingUntilDone(
    request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Recognizer>.State
      in
      return try op._extractStatus(Recognizer.self)
    }
    let rawOp = try await self.createRecognizer(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Recognizers.
  ///
  /// @Snippet(path: "Speech_ListRecognizers")
  public func listRecognizers(
    request: ListRecognizersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse {
    try await self.inner.listRecognizers(request: request, options: options)
  }

  /// Returns the requested
  /// [Recognizer][google.cloud.speech.v2.Recognizer]. Fails with
  /// [NOT_FOUND][google.rpc.Code.NOT_FOUND] if the requested Recognizer doesn't
  /// exist.
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_GetRecognizer")
  public func getRecognizer(
    request: GetRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Recognizer {
    try await self.inner.getRecognizer(request: request, options: options)
  }

  /// Updates the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_UpdateRecognizer")
  public func updateRecognizer(
    request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateRecognizer(request: request, options: options)
  }

  /// Updates the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_UpdateRecognizer")
  public func updateRecognizerPollingUntilDone(
    request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Recognizer>.State
      in
      return try op._extractStatus(Recognizer.self)
    }
    let rawOp = try await self.updateRecognizer(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_DeleteRecognizer")
  public func deleteRecognizer(
    request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRecognizer(request: request, options: options)
  }

  /// Deletes the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_DeleteRecognizer")
  public func deleteRecognizerPollingUntilDone(
    request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Recognizer>.State
      in
      return try op._extractStatus(Recognizer.self)
    }
    let rawOp = try await self.deleteRecognizer(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeletes the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_UndeleteRecognizer")
  public func undeleteRecognizer(
    request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeleteRecognizer(request: request, options: options)
  }

  /// Undeletes the [Recognizer][google.cloud.speech.v2.Recognizer].
  ///
  /// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
  ///
  /// @Snippet(path: "Speech_UndeleteRecognizer")
  public func undeleteRecognizerPollingUntilDone(
    request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Recognizer>.State
      in
      return try op._extractStatus(Recognizer.self)
    }
    let rawOp = try await self.undeleteRecognizer(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Performs synchronous Speech recognition: receive results after all audio
  /// has been sent and processed.
  ///
  /// @Snippet(path: "Speech_Recognize")
  public func recognize(
    request: RecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
    try await self.inner.recognize(request: request, options: options)
  }

  /// Performs batch asynchronous speech recognition: send a request with N
  /// audio files and receive a long running operation that can be polled to see
  /// when the transcriptions are finished.
  ///
  /// @Snippet(path: "Speech_BatchRecognize")
  public func batchRecognize(
    request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchRecognize(request: request, options: options)
  }

  /// Performs batch asynchronous speech recognition: send a request with N
  /// audio files and receive a long running operation that can be polled to see
  /// when the transcriptions are finished.
  ///
  /// @Snippet(path: "Speech_BatchRecognize")
  public func batchRecognizePollingUntilDone(
    request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchRecognizeResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<BatchRecognizeResponse>.State in
      return try op._extractStatus(BatchRecognizeResponse.self)
    }
    let rawOp = try await self.batchRecognize(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchRecognizeResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested [Config][google.cloud.speech.v2.Config].
  ///
  /// [google.cloud.speech.v2.Config]: <doc:Config>
  ///
  /// @Snippet(path: "Speech_GetConfig")
  public func getConfig(
    request: GetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Config {
    try await self.inner.getConfig(request: request, options: options)
  }

  /// Updates the [Config][google.cloud.speech.v2.Config].
  ///
  /// [google.cloud.speech.v2.Config]: <doc:Config>
  ///
  /// @Snippet(path: "Speech_UpdateConfig")
  public func updateConfig(
    request: UpdateConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Config {
    try await self.inner.updateConfig(request: request, options: options)
  }

  /// Creates a [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_CreateCustomClass")
  public func createCustomClass(
    request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCustomClass(request: request, options: options)
  }

  /// Creates a [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_CreateCustomClass")
  public func createCustomClassPollingUntilDone(
    request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      return try op._extractStatus(CustomClass.self)
    }
    let rawOp = try await self.createCustomClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists CustomClasses.
  ///
  /// @Snippet(path: "Speech_ListCustomClasses")
  public func listCustomClasses(
    request: ListCustomClassesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse {
    try await self.inner.listCustomClasses(request: request, options: options)
  }

  /// Returns the requested
  /// [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_GetCustomClass")
  public func getCustomClass(
    request: GetCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.CustomClass {
    try await self.inner.getCustomClass(request: request, options: options)
  }

  /// Updates the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_UpdateCustomClass")
  public func updateCustomClass(
    request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCustomClass(request: request, options: options)
  }

  /// Updates the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_UpdateCustomClass")
  public func updateCustomClassPollingUntilDone(
    request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      return try op._extractStatus(CustomClass.self)
    }
    let rawOp = try await self.updateCustomClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_DeleteCustomClass")
  public func deleteCustomClass(
    request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCustomClass(request: request, options: options)
  }

  /// Deletes the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_DeleteCustomClass")
  public func deleteCustomClassPollingUntilDone(
    request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      return try op._extractStatus(CustomClass.self)
    }
    let rawOp = try await self.deleteCustomClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeletes the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_UndeleteCustomClass")
  public func undeleteCustomClass(
    request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeleteCustomClass(request: request, options: options)
  }

  /// Undeletes the [CustomClass][google.cloud.speech.v2.CustomClass].
  ///
  /// [google.cloud.speech.v2.CustomClass]: <doc:CustomClass>
  ///
  /// @Snippet(path: "Speech_UndeleteCustomClass")
  public func undeleteCustomClassPollingUntilDone(
    request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      return try op._extractStatus(CustomClass.self)
    }
    let rawOp = try await self.undeleteCustomClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_CreatePhraseSet")
  public func createPhraseSet(
    request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createPhraseSet(request: request, options: options)
  }

  /// Creates a [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_CreatePhraseSet")
  public func createPhraseSetPollingUntilDone(
    request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State
      in
      return try op._extractStatus(PhraseSet.self)
    }
    let rawOp = try await self.createPhraseSet(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists PhraseSets.
  ///
  /// @Snippet(path: "Speech_ListPhraseSets")
  public func listPhraseSets(
    request: ListPhraseSetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse {
    try await self.inner.listPhraseSets(request: request, options: options)
  }

  /// Returns the requested
  /// [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_GetPhraseSet")
  public func getPhraseSet(
    request: GetPhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.PhraseSet {
    try await self.inner.getPhraseSet(request: request, options: options)
  }

  /// Updates the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_UpdatePhraseSet")
  public func updatePhraseSet(
    request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updatePhraseSet(request: request, options: options)
  }

  /// Updates the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_UpdatePhraseSet")
  public func updatePhraseSetPollingUntilDone(
    request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State
      in
      return try op._extractStatus(PhraseSet.self)
    }
    let rawOp = try await self.updatePhraseSet(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_DeletePhraseSet")
  public func deletePhraseSet(
    request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deletePhraseSet(request: request, options: options)
  }

  /// Deletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_DeletePhraseSet")
  public func deletePhraseSetPollingUntilDone(
    request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State
      in
      return try op._extractStatus(PhraseSet.self)
    }
    let rawOp = try await self.deletePhraseSet(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_UndeletePhraseSet")
  public func undeletePhraseSet(
    request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeletePhraseSet(request: request, options: options)
  }

  /// Undeletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
  ///
  /// [google.cloud.speech.v2.PhraseSet]: <doc:PhraseSet>
  ///
  /// @Snippet(path: "Speech_UndeletePhraseSet")
  public func undeletePhraseSetPollingUntilDone(
    request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State
      in
      return try op._extractStatus(PhraseSet.self)
    }
    let rawOp = try await self.undeletePhraseSet(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "Speech_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Speech_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Speech_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Speech_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Speech_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Speech_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SpeechClient`.
  ///
  /// To mock `SpeechClient` change your functions to receive
  /// `some SpeechProtocol` or `any SpeechProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SpeechProtocol: Sendable {
    /// See `SpeechClient.createRecognizer`.
    func createRecognizerPollingUntilDone(request: CreateRecognizerRequest) async throws
      -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.createRecognizer`.
    func createRecognizerPollingUntilDone(
      parent: Swift.String,
      recognizer: Recognizer?,
      recognizerId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.updateRecognizer`.
    func updateRecognizerPollingUntilDone(request: UpdateRecognizerRequest) async throws
      -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.updateRecognizer`.
    func updateRecognizerPollingUntilDone(
      recognizer: Recognizer?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.deleteRecognizer`.
    func deleteRecognizerPollingUntilDone(request: DeleteRecognizerRequest) async throws
      -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.deleteRecognizer`.
    func deleteRecognizerPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.undeleteRecognizer`.
    func undeleteRecognizerPollingUntilDone(request: UndeleteRecognizerRequest) async throws
      -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.undeleteRecognizer`.
    func undeleteRecognizerPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.batchRecognize`.
    func batchRecognizePollingUntilDone(request: BatchRecognizeRequest) async throws
      -> any GoogleGax.PollableOperation<BatchRecognizeResponse>

    /// See `SpeechClient.batchRecognize`.
    func batchRecognizePollingUntilDone(
      recognizer: Swift.String,
      config: RecognitionConfig?,
      configMask: GoogleWKT.WKTFieldMask?,
      files: [BatchRecognizeFileMetadata],
    ) async throws -> any GoogleGax.PollableOperation<BatchRecognizeResponse>

    /// See `SpeechClient.createCustomClass`.
    func createCustomClassPollingUntilDone(request: CreateCustomClassRequest) async throws
      -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.createCustomClass`.
    func createCustomClassPollingUntilDone(
      parent: Swift.String,
      customClass: CustomClass?,
      customClassId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.updateCustomClass`.
    func updateCustomClassPollingUntilDone(request: UpdateCustomClassRequest) async throws
      -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.updateCustomClass`.
    func updateCustomClassPollingUntilDone(
      customClass: CustomClass?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.deleteCustomClass`.
    func deleteCustomClassPollingUntilDone(request: DeleteCustomClassRequest) async throws
      -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.deleteCustomClass`.
    func deleteCustomClassPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.undeleteCustomClass`.
    func undeleteCustomClassPollingUntilDone(request: UndeleteCustomClassRequest) async throws
      -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.undeleteCustomClass`.
    func undeleteCustomClassPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.createPhraseSet`.
    func createPhraseSetPollingUntilDone(request: CreatePhraseSetRequest) async throws
      -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.createPhraseSet`.
    func createPhraseSetPollingUntilDone(
      parent: Swift.String,
      phraseSet: PhraseSet?,
      phraseSetId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.updatePhraseSet`.
    func updatePhraseSetPollingUntilDone(request: UpdatePhraseSetRequest) async throws
      -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.updatePhraseSet`.
    func updatePhraseSetPollingUntilDone(
      phraseSet: PhraseSet?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.deletePhraseSet`.
    func deletePhraseSetPollingUntilDone(request: DeletePhraseSetRequest) async throws
      -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.deletePhraseSet`.
    func deletePhraseSetPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.undeletePhraseSet`.
    func undeletePhraseSetPollingUntilDone(request: UndeletePhraseSetRequest) async throws
      -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.undeletePhraseSet`.
    func undeletePhraseSetPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.createRecognizer`.
    func createRecognizer(
      request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.createRecognizer`.
    func createRecognizerPollingUntilDone(
      request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.listRecognizers`.
    func listRecognizers(
      request: ListRecognizersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse

    /// See `SpeechClient.getRecognizer`.
    func getRecognizer(
      request: GetRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Recognizer

    /// See `SpeechClient.updateRecognizer`.
    func updateRecognizer(
      request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.updateRecognizer`.
    func updateRecognizerPollingUntilDone(
      request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.deleteRecognizer`.
    func deleteRecognizer(
      request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.deleteRecognizer`.
    func deleteRecognizerPollingUntilDone(
      request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.undeleteRecognizer`.
    func undeleteRecognizer(
      request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.undeleteRecognizer`.
    func undeleteRecognizerPollingUntilDone(
      request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Recognizer>

    /// See `SpeechClient.recognize`.
    func recognize(
      request: RecognizeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.RecognizeResponse

    /// See `SpeechClient.batchRecognize`.
    func batchRecognize(
      request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.batchRecognize`.
    func batchRecognizePollingUntilDone(
      request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<BatchRecognizeResponse>

    /// See `SpeechClient.getConfig`.
    func getConfig(
      request: GetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config

    /// See `SpeechClient.updateConfig`.
    func updateConfig(
      request: UpdateConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config

    /// See `SpeechClient.createCustomClass`.
    func createCustomClass(
      request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.createCustomClass`.
    func createCustomClassPollingUntilDone(
      request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.listCustomClasses`.
    func listCustomClasses(
      request: ListCustomClassesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse

    /// See `SpeechClient.getCustomClass`.
    func getCustomClass(
      request: GetCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.CustomClass

    /// See `SpeechClient.updateCustomClass`.
    func updateCustomClass(
      request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.updateCustomClass`.
    func updateCustomClassPollingUntilDone(
      request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.deleteCustomClass`.
    func deleteCustomClass(
      request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.deleteCustomClass`.
    func deleteCustomClassPollingUntilDone(
      request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.undeleteCustomClass`.
    func undeleteCustomClass(
      request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.undeleteCustomClass`.
    func undeleteCustomClassPollingUntilDone(
      request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<CustomClass>

    /// See `SpeechClient.createPhraseSet`.
    func createPhraseSet(
      request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.createPhraseSet`.
    func createPhraseSetPollingUntilDone(
      request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.listPhraseSets`.
    func listPhraseSets(
      request: ListPhraseSetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse

    /// See `SpeechClient.getPhraseSet`.
    func getPhraseSet(
      request: GetPhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.PhraseSet

    /// See `SpeechClient.updatePhraseSet`.
    func updatePhraseSet(
      request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.updatePhraseSet`.
    func updatePhraseSetPollingUntilDone(
      request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.deletePhraseSet`.
    func deletePhraseSet(
      request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.deletePhraseSet`.
    func deletePhraseSetPollingUntilDone(
      request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.undeletePhraseSet`.
    func undeletePhraseSet(
      request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SpeechClient.undeletePhraseSet`.
    func undeletePhraseSetPollingUntilDone(
      request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PhraseSet>

    /// See `SpeechClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `SpeechClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `SpeechClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `SpeechClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `SpeechClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.SpeechProtocol {
  public func createRecognizer(request: CreateRecognizerRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createRecognizer(request: request, options: .init())
  }

  public func createRecognizer(
    request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createRecognizerPollingUntilDone(request: CreateRecognizerRequest) async throws
    -> any GoogleGax.PollableOperation<Recognizer>
  {
    try await self.createRecognizerPollingUntilDone(request: request, options: .init())
  }

  public func createRecognizerPollingUntilDone(
    request: CreateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createRecognizerPollingUntilDone(
    parent: Swift.String,
    recognizer: Recognizer?,
    recognizerId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let request = CreateRecognizerRequest().with {
      $0.parent = parent
      $0.recognizer = recognizer
      $0.recognizerId = recognizerId
    }
    return try await self.createRecognizerPollingUntilDone(request: request)
  }

  public func listRecognizers(request: ListRecognizersRequest) async throws
    -> GoogleCloudSpeechV2.ListRecognizersResponse
  {
    try await self.listRecognizers(request: request, options: .init())
  }

  public func listRecognizers(
    request: ListRecognizersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRecognizersByItems(
    request: ListRecognizersRequest
  ) -> any AsyncSequence<Recognizer, Swift.Error> & Sendable {
    self.listRecognizersByItems(request: request, options: .init())
  }

  /// Lists Recognizers.
  ///
  /// @Snippet(path: "Speech_ListRecognizers")
  public func listRecognizersByItems(
    request: ListRecognizersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Recognizer, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse in
      var request = request
      request.pageToken = token
      return try await self.listRecognizers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRecognizersByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Recognizer, Swift.Error> & Sendable {
    let request = ListRecognizersRequest().with {
      $0.parent = parent
    }
    return self.listRecognizersByItems(request: request)
  }

  public func getRecognizer(request: GetRecognizerRequest) async throws
    -> GoogleCloudSpeechV2.Recognizer
  {
    try await self.getRecognizer(request: request, options: .init())
  }

  public func getRecognizer(
    request: GetRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Recognizer {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRecognizer(
    name: Swift.String,
  ) async throws -> GoogleCloudSpeechV2.Recognizer {
    let request = GetRecognizerRequest().with {
      $0.name = name
    }
    return try await self.getRecognizer(request: request)
  }

  public func updateRecognizer(request: UpdateRecognizerRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateRecognizer(request: request, options: .init())
  }

  public func updateRecognizer(
    request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateRecognizerPollingUntilDone(request: UpdateRecognizerRequest) async throws
    -> any GoogleGax.PollableOperation<Recognizer>
  {
    try await self.updateRecognizerPollingUntilDone(request: request, options: .init())
  }

  public func updateRecognizerPollingUntilDone(
    request: UpdateRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateRecognizerPollingUntilDone(
    recognizer: Recognizer?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let request = UpdateRecognizerRequest().with {
      $0.recognizer = recognizer
      $0.updateMask = updateMask
    }
    return try await self.updateRecognizerPollingUntilDone(request: request)
  }

  public func deleteRecognizer(request: DeleteRecognizerRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteRecognizer(request: request, options: .init())
  }

  public func deleteRecognizer(
    request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteRecognizerPollingUntilDone(request: DeleteRecognizerRequest) async throws
    -> any GoogleGax.PollableOperation<Recognizer>
  {
    try await self.deleteRecognizerPollingUntilDone(request: request, options: .init())
  }

  public func deleteRecognizerPollingUntilDone(
    request: DeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRecognizerPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let request = DeleteRecognizerRequest().with {
      $0.name = name
    }
    return try await self.deleteRecognizerPollingUntilDone(request: request)
  }

  public func undeleteRecognizer(request: UndeleteRecognizerRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.undeleteRecognizer(request: request, options: .init())
  }

  public func undeleteRecognizer(
    request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func undeleteRecognizerPollingUntilDone(request: UndeleteRecognizerRequest) async throws
    -> any GoogleGax.PollableOperation<Recognizer>
  {
    try await self.undeleteRecognizerPollingUntilDone(request: request, options: .init())
  }

  public func undeleteRecognizerPollingUntilDone(
    request: UndeleteRecognizerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Recognizer>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func undeleteRecognizerPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Recognizer> {
    let request = UndeleteRecognizerRequest().with {
      $0.name = name
    }
    return try await self.undeleteRecognizerPollingUntilDone(request: request)
  }

  public func recognize(request: RecognizeRequest) async throws
    -> GoogleCloudSpeechV2.RecognizeResponse
  {
    try await self.recognize(request: request, options: .init())
  }

  public func recognize(
    request: RecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func recognize(
    recognizer: Swift.String,
    config: RecognitionConfig?,
    configMask: GoogleWKT.WKTFieldMask?,
    content: Foundation.Data,
  ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
    let request = RecognizeRequest().with {
      $0.recognizer = recognizer
      $0.config = config
      $0.configMask = configMask
      $0.audioSource = .content(content)
    }
    return try await self.recognize(request: request)
  }

  public func recognize(
    recognizer: Swift.String,
    config: RecognitionConfig?,
    configMask: GoogleWKT.WKTFieldMask?,
    uri: Swift.String,
  ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
    let request = RecognizeRequest().with {
      $0.recognizer = recognizer
      $0.config = config
      $0.configMask = configMask
      $0.audioSource = .uri(uri)
    }
    return try await self.recognize(request: request)
  }

  public func batchRecognize(request: BatchRecognizeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchRecognize(request: request, options: .init())
  }

  public func batchRecognize(
    request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchRecognizePollingUntilDone(request: BatchRecognizeRequest) async throws
    -> any GoogleGax.PollableOperation<BatchRecognizeResponse>
  {
    try await self.batchRecognizePollingUntilDone(request: request, options: .init())
  }

  public func batchRecognizePollingUntilDone(
    request: BatchRecognizeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchRecognizeResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchRecognizeResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchRecognizePollingUntilDone(
    recognizer: Swift.String,
    config: RecognitionConfig?,
    configMask: GoogleWKT.WKTFieldMask?,
    files: [BatchRecognizeFileMetadata],
  ) async throws -> any GoogleGax.PollableOperation<BatchRecognizeResponse> {
    let request = BatchRecognizeRequest().with {
      $0.recognizer = recognizer
      $0.config = config
      $0.configMask = configMask
      $0.files = files
    }
    return try await self.batchRecognizePollingUntilDone(request: request)
  }

  public func getConfig(request: GetConfigRequest) async throws -> GoogleCloudSpeechV2.Config {
    try await self.getConfig(request: request, options: .init())
  }

  public func getConfig(
    request: GetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Config {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudSpeechV2.Config {
    let request = GetConfigRequest().with {
      $0.name = name
    }
    return try await self.getConfig(request: request)
  }

  public func updateConfig(request: UpdateConfigRequest) async throws -> GoogleCloudSpeechV2.Config
  {
    try await self.updateConfig(request: request, options: .init())
  }

  public func updateConfig(
    request: UpdateConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.Config {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConfig(
    config: Config?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudSpeechV2.Config {
    let request = UpdateConfigRequest().with {
      $0.config = config
      $0.updateMask = updateMask
    }
    return try await self.updateConfig(request: request)
  }

  public func createCustomClass(request: CreateCustomClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCustomClass(request: request, options: .init())
  }

  public func createCustomClass(
    request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createCustomClassPollingUntilDone(request: CreateCustomClassRequest) async throws
    -> any GoogleGax.PollableOperation<CustomClass>
  {
    try await self.createCustomClassPollingUntilDone(request: request, options: .init())
  }

  public func createCustomClassPollingUntilDone(
    request: CreateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCustomClassPollingUntilDone(
    parent: Swift.String,
    customClass: CustomClass?,
    customClassId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let request = CreateCustomClassRequest().with {
      $0.parent = parent
      $0.customClass = customClass
      $0.customClassId = customClassId
    }
    return try await self.createCustomClassPollingUntilDone(request: request)
  }

  public func listCustomClasses(request: ListCustomClassesRequest) async throws
    -> GoogleCloudSpeechV2.ListCustomClassesResponse
  {
    try await self.listCustomClasses(request: request, options: .init())
  }

  public func listCustomClasses(
    request: ListCustomClassesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCustomClassesByItems(
    request: ListCustomClassesRequest
  ) -> any AsyncSequence<CustomClass, Swift.Error> & Sendable {
    self.listCustomClassesByItems(request: request, options: .init())
  }

  /// Lists CustomClasses.
  ///
  /// @Snippet(path: "Speech_ListCustomClasses")
  public func listCustomClassesByItems(
    request: ListCustomClassesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CustomClass, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listCustomClasses(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCustomClassesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<CustomClass, Swift.Error> & Sendable {
    let request = ListCustomClassesRequest().with {
      $0.parent = parent
    }
    return self.listCustomClassesByItems(request: request)
  }

  public func getCustomClass(request: GetCustomClassRequest) async throws
    -> GoogleCloudSpeechV2.CustomClass
  {
    try await self.getCustomClass(request: request, options: .init())
  }

  public func getCustomClass(
    request: GetCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.CustomClass {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCustomClass(
    name: Swift.String,
  ) async throws -> GoogleCloudSpeechV2.CustomClass {
    let request = GetCustomClassRequest().with {
      $0.name = name
    }
    return try await self.getCustomClass(request: request)
  }

  public func updateCustomClass(request: UpdateCustomClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCustomClass(request: request, options: .init())
  }

  public func updateCustomClass(
    request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateCustomClassPollingUntilDone(request: UpdateCustomClassRequest) async throws
    -> any GoogleGax.PollableOperation<CustomClass>
  {
    try await self.updateCustomClassPollingUntilDone(request: request, options: .init())
  }

  public func updateCustomClassPollingUntilDone(
    request: UpdateCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCustomClassPollingUntilDone(
    customClass: CustomClass?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let request = UpdateCustomClassRequest().with {
      $0.customClass = customClass
      $0.updateMask = updateMask
    }
    return try await self.updateCustomClassPollingUntilDone(request: request)
  }

  public func deleteCustomClass(request: DeleteCustomClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCustomClass(request: request, options: .init())
  }

  public func deleteCustomClass(
    request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteCustomClassPollingUntilDone(request: DeleteCustomClassRequest) async throws
    -> any GoogleGax.PollableOperation<CustomClass>
  {
    try await self.deleteCustomClassPollingUntilDone(request: request, options: .init())
  }

  public func deleteCustomClassPollingUntilDone(
    request: DeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCustomClassPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let request = DeleteCustomClassRequest().with {
      $0.name = name
    }
    return try await self.deleteCustomClassPollingUntilDone(request: request)
  }

  public func undeleteCustomClass(request: UndeleteCustomClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.undeleteCustomClass(request: request, options: .init())
  }

  public func undeleteCustomClass(
    request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func undeleteCustomClassPollingUntilDone(request: UndeleteCustomClassRequest) async throws
    -> any GoogleGax.PollableOperation<CustomClass>
  {
    try await self.undeleteCustomClassPollingUntilDone(request: request, options: .init())
  }

  public func undeleteCustomClassPollingUntilDone(
    request: UndeleteCustomClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<CustomClass>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func undeleteCustomClassPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<CustomClass> {
    let request = UndeleteCustomClassRequest().with {
      $0.name = name
    }
    return try await self.undeleteCustomClassPollingUntilDone(request: request)
  }

  public func createPhraseSet(request: CreatePhraseSetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createPhraseSet(request: request, options: .init())
  }

  public func createPhraseSet(
    request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createPhraseSetPollingUntilDone(request: CreatePhraseSetRequest) async throws
    -> any GoogleGax.PollableOperation<PhraseSet>
  {
    try await self.createPhraseSetPollingUntilDone(request: request, options: .init())
  }

  public func createPhraseSetPollingUntilDone(
    request: CreatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createPhraseSetPollingUntilDone(
    parent: Swift.String,
    phraseSet: PhraseSet?,
    phraseSetId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let request = CreatePhraseSetRequest().with {
      $0.parent = parent
      $0.phraseSet = phraseSet
      $0.phraseSetId = phraseSetId
    }
    return try await self.createPhraseSetPollingUntilDone(request: request)
  }

  public func listPhraseSets(request: ListPhraseSetsRequest) async throws
    -> GoogleCloudSpeechV2.ListPhraseSetsResponse
  {
    try await self.listPhraseSets(request: request, options: .init())
  }

  public func listPhraseSets(
    request: ListPhraseSetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPhraseSetsByItems(
    request: ListPhraseSetsRequest
  ) -> any AsyncSequence<PhraseSet, Swift.Error> & Sendable {
    self.listPhraseSetsByItems(request: request, options: .init())
  }

  /// Lists PhraseSets.
  ///
  /// @Snippet(path: "Speech_ListPhraseSets")
  public func listPhraseSetsByItems(
    request: ListPhraseSetsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PhraseSet, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse in
      var request = request
      request.pageToken = token
      return try await self.listPhraseSets(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPhraseSetsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<PhraseSet, Swift.Error> & Sendable {
    let request = ListPhraseSetsRequest().with {
      $0.parent = parent
    }
    return self.listPhraseSetsByItems(request: request)
  }

  public func getPhraseSet(request: GetPhraseSetRequest) async throws
    -> GoogleCloudSpeechV2.PhraseSet
  {
    try await self.getPhraseSet(request: request, options: .init())
  }

  public func getPhraseSet(
    request: GetPhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSpeechV2.PhraseSet {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPhraseSet(
    name: Swift.String,
  ) async throws -> GoogleCloudSpeechV2.PhraseSet {
    let request = GetPhraseSetRequest().with {
      $0.name = name
    }
    return try await self.getPhraseSet(request: request)
  }

  public func updatePhraseSet(request: UpdatePhraseSetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updatePhraseSet(request: request, options: .init())
  }

  public func updatePhraseSet(
    request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updatePhraseSetPollingUntilDone(request: UpdatePhraseSetRequest) async throws
    -> any GoogleGax.PollableOperation<PhraseSet>
  {
    try await self.updatePhraseSetPollingUntilDone(request: request, options: .init())
  }

  public func updatePhraseSetPollingUntilDone(
    request: UpdatePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updatePhraseSetPollingUntilDone(
    phraseSet: PhraseSet?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let request = UpdatePhraseSetRequest().with {
      $0.phraseSet = phraseSet
      $0.updateMask = updateMask
    }
    return try await self.updatePhraseSetPollingUntilDone(request: request)
  }

  public func deletePhraseSet(request: DeletePhraseSetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deletePhraseSet(request: request, options: .init())
  }

  public func deletePhraseSet(
    request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deletePhraseSetPollingUntilDone(request: DeletePhraseSetRequest) async throws
    -> any GoogleGax.PollableOperation<PhraseSet>
  {
    try await self.deletePhraseSetPollingUntilDone(request: request, options: .init())
  }

  public func deletePhraseSetPollingUntilDone(
    request: DeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deletePhraseSetPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let request = DeletePhraseSetRequest().with {
      $0.name = name
    }
    return try await self.deletePhraseSetPollingUntilDone(request: request)
  }

  public func undeletePhraseSet(request: UndeletePhraseSetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.undeletePhraseSet(request: request, options: .init())
  }

  public func undeletePhraseSet(
    request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func undeletePhraseSetPollingUntilDone(request: UndeletePhraseSetRequest) async throws
    -> any GoogleGax.PollableOperation<PhraseSet>
  {
    try await self.undeletePhraseSetPollingUntilDone(request: request, options: .init())
  }

  public func undeletePhraseSetPollingUntilDone(
    request: UndeletePhraseSetRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<PhraseSet>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func undeletePhraseSetPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<PhraseSet> {
    let request = UndeletePhraseSetRequest().with {
      $0.name = name
    }
    return try await self.undeletePhraseSetPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "Speech_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Speech_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
