// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Provides "hints" to the speech recognizer to favor specific words and phrases
/// in the results. PhraseSets can be specified as an inline resource, or a
/// reference to an existing PhraseSet resource.
public struct SpeechAdaptation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A list of inline or referenced PhraseSets.
  public var phraseSets: [SpeechAdaptation.AdaptationPhraseSet] = []

  /// A list of inline CustomClasses. Existing CustomClass resources can be
  /// referenced directly in a PhraseSet.
  public var customClasses: [CustomClass] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SpeechAdaptation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpeechAdaptation().with { $0.phraseSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let phraseSets = CodingKeys(stringValue: "phraseSets")
    static let customClasses = CodingKeys(stringValue: "customClasses")

    static let _knownKeys: Set<Swift.String> = [
      "phraseSets",
      "customClasses",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SpeechAdaptation.AdaptationPhraseSet].self, forKey: .phraseSets)
    {
      self.phraseSets = value
    }
    if let value = try container.decodeIfPresent([CustomClass].self, forKey: .customClasses) {
      self.customClasses = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.phraseSets, forKey: .phraseSets)
    try container.encode(self.customClasses, forKey: .customClasses)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A biasing PhraseSet, which can be either a string referencing the name of
  /// an existing PhraseSets resource, or an inline definition of a PhraseSet.
  public struct AdaptationPhraseSet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var value: ValueOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AdaptationPhraseSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AdaptationPhraseSet().with { $0.phraseSet = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let phraseSet = CodingKeys(stringValue: "phraseSet")
      static let inlinePhraseSet = CodingKeys(stringValue: "inlinePhraseSet")

      static let _knownKeys: Set<Swift.String> = [
        "phraseSet",
        "inlinePhraseSet",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var value: ValueOneOf? = nil
      let valueCheckAndSet = {
        if value != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'value'"))
        }
        value = $0
      }
      if let phraseSet = try container.decodeIfPresent(Swift.String.self, forKey: .phraseSet) {
        try valueCheckAndSet(.phraseSet(phraseSet))
      }
      if let inlinePhraseSet = try container.decodeIfPresent(
        PhraseSet.self, forKey: .inlinePhraseSet)
      {
        try valueCheckAndSet(.inlinePhraseSet(inlinePhraseSet))
      }
      self.value = value
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.value {
        switch choice {
        case .phraseSet(let value):
          try container.encode(value, forKey: .phraseSet)
        case .inlinePhraseSet(let value):
          try container.encode(value, forKey: .inlinePhraseSet)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum ValueOneOf: Codable, Equatable, Sendable {
      /// The name of an existing PhraseSet resource. The user must have read
      /// access to the resource and it must not be deleted.
      case phraseSet(Swift.String)
      /// An inline defined PhraseSet.
      indirect case inlinePhraseSet(PhraseSet)
    }

    /// The type URL for `AdaptationPhraseSet`: `"type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation.AdaptationPhraseSet"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation.AdaptationPhraseSet"
    }

    /// Initialize an instance of `AdaptationPhraseSet` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation.AdaptationPhraseSet"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `AdaptationPhraseSet` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `SpeechAdaptation`: `"type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation"
  }

  /// Initialize an instance of `SpeechAdaptation` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `SpeechAdaptation` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
