// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// `StreamingRecognizeResponse` is the only message returned to the client by
/// `StreamingRecognize`. A series of zero or more `StreamingRecognizeResponse`
/// messages are streamed back to the client. If there is no recognizable
/// audio then no messages are streamed back to the client.
///
/// Here are some examples of `StreamingRecognizeResponse`s that might
/// be returned while processing audio:
///
/// 1. results { alternatives { transcript: "tube" } stability: 0.01 }
///
/// 2. results { alternatives { transcript: "to be a" } stability: 0.01 }
///
/// 3. results { alternatives { transcript: "to be" } stability: 0.9 }
///    results { alternatives { transcript: " or not to be" } stability: 0.01 }
///
/// 4. results { alternatives { transcript: "to be or not to be"
///                             confidence: 0.92 }
///              alternatives { transcript: "to bee or not to bee" }
///              is_final: true }
///
/// 5. results { alternatives { transcript: " that's" } stability: 0.01 }
///
/// 6. results { alternatives { transcript: " that is" } stability: 0.9 }
///    results { alternatives { transcript: " the question" } stability: 0.01 }
///
/// 7. results { alternatives { transcript: " that is the question"
///                             confidence: 0.98 }
///              alternatives { transcript: " that was the question" }
///              is_final: true }
///
/// Notes:
///
/// - Only two of the above responses #4 and #7 contain final results; they are
///   indicated by `is_final: true`. Concatenating these together generates the
///   full transcript: "to be or not to be that is the question".
///
/// - The others contain interim `results`. #3 and #6 contain two interim
///   `results`: the first portion has a high stability and is less likely to
///   change; the second portion has a low stability and is very likely to
///   change. A UI designer might choose to show only high stability `results`.
///
/// - The specific `stability` and `confidence` values shown above are only for
///   illustrative purposes. Actual values may vary.
///
/// - In each response, only one of these fields will be set:
///     `error`,
///     `speech_event_type`, or
///     one or more (repeated) `results`.
public struct StreamingRecognizeResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// This repeated list contains zero or more results that
  /// correspond to consecutive portions of the audio currently being processed.
  /// It contains zero or one
  /// [is_final][google.cloud.speech.v2.StreamingRecognitionResult.is_final]=`true`
  /// result (the newly settled portion), followed by zero or more
  /// [is_final][google.cloud.speech.v2.StreamingRecognitionResult.is_final]=`false`
  /// results (the interim results).
  ///
  /// [google.cloud.speech.v2.StreamingRecognitionResult.is_final]: <doc:StreamingRecognitionResult/isFinal>
  public var results: [StreamingRecognitionResult] = []

  /// Indicates the type of speech event.
  public var speechEventType: StreamingRecognizeResponse.SpeechEventType =
    StreamingRecognizeResponse.SpeechEventType()

  /// Time offset between the beginning of the audio and event emission.
  public var speechEventOffset: GoogleWKT.WKTDuration? = nil

  /// Metadata about the recognition.
  public var metadata: RecognitionResponseMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StreamingRecognizeResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingRecognizeResponse().with { $0.results = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let results = CodingKeys(stringValue: "results")
    static let speechEventType = CodingKeys(stringValue: "speechEventType")
    static let speechEventOffset = CodingKeys(stringValue: "speechEventOffset")
    static let metadata = CodingKeys(stringValue: "metadata")

    static let _knownKeys: Set<Swift.String> = [
      "results",
      "speechEventType",
      "speechEventOffset",
      "metadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [StreamingRecognitionResult].self, forKey: .results)
    {
      self.results = value
    }
    if let value = try container.decodeIfPresent(
      StreamingRecognizeResponse.SpeechEventType.self, forKey: .speechEventType)
    {
      self.speechEventType = value
    }
    self.speechEventOffset = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .speechEventOffset)
    self.metadata = try container.decodeIfPresent(
      RecognitionResponseMetadata.self, forKey: .metadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.results, forKey: .results)
    try container.encode(self.speechEventType, forKey: .speechEventType)
    try container.encodeIfPresent(self.speechEventOffset, forKey: .speechEventOffset)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates the type of speech event.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SpeechEventType: Codable, Equatable, Sendable {
    /// No speech event specified.
    case unspecified
    /// This event indicates that the server has detected the end of the user's
    /// speech utterance and expects no additional speech. Therefore, the server
    /// will not process additional audio and will close the gRPC bidirectional
    /// stream. This event is only sent if there was a force cutoff due to
    /// silence being detected early. This event is only available through the
    /// `latest_short` [model][google.cloud.speech.v2.Recognizer.model].
    ///
    /// [google.cloud.speech.v2.Recognizer.model]: <doc:Recognizer/model>
    case endOfSingleUtterance
    /// This event indicates that the server has detected the beginning of human
    /// voice activity in the stream. This event can be returned multiple times
    /// if speech starts and stops repeatedly throughout the stream. This event
    /// is only sent if `voice_activity_events` is set to true.
    case speechActivityBegin
    /// This event indicates that the server has detected the end of human voice
    /// activity in the stream. This event can be returned multiple times if
    /// speech starts and stops repeatedly throughout the stream. This event is
    /// only sent if `voice_activity_events` is set to true.
    case speechActivityEnd
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .endOfSingleUtterance: return 1
      case .speechActivityBegin: return 2
      case .speechActivityEnd: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SPEECH_EVENT_TYPE_UNSPECIFIED"
      case .endOfSingleUtterance: return "END_OF_SINGLE_UTTERANCE"
      case .speechActivityBegin: return "SPEECH_ACTIVITY_BEGIN"
      case .speechActivityEnd: return "SPEECH_ACTIVITY_END"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SpeechEventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SPEECH_EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "END_OF_SINGLE_UTTERANCE": self = .endOfSingleUtterance
      case "SPEECH_ACTIVITY_BEGIN": self = .speechActivityBegin
      case "SPEECH_ACTIVITY_END": self = .speechActivityEnd
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SpeechEventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .endOfSingleUtterance
      case 2: self = .speechActivityBegin
      case 3: self = .speechActivityEnd
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SPEECH_EVENT_TYPE_UNSPECIFIED")
      case .endOfSingleUtterance: return try container.encode("END_OF_SINGLE_UTTERANCE")
      case .speechActivityBegin: return try container.encode("SPEECH_ACTIVITY_BEGIN")
      case .speechActivityEnd: return try container.encode("SPEECH_ACTIVITY_END")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.StreamingRecognizeResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
